#
#      print_head "Download Dependencies"
#      cd /app
#      go mod init dispatch  &>>${LOG}
#      status_check
#
#      print_head "Get the Dependencies"
#      go get &>>${LOG}
#      status_check
#
#      print_head "Build the Dependencies"
#      go build &>>${LOG}
#      status_check
#
#      print_head "Update Passwords in Service File"
#      sed -i -e "s/roboshop_rabbitmq_password/${roboshop_rabbitmq_password}/" ${script_location}/files/${component}.service  &>>${LOG}
#      status_check
#
#      SYSTEMD_SETUP
#



- name: Install GoLang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App pre-Req
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: Download Dependencies
  ansible.builtin.shell: go mod init dispatch

- name: Get the Dependencies
  ansible.builtin.shell: go get

- name: Get the Dependencies
  ansible.builtin.shell: go build


- name: SystemD setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load


#- name: Download golang dependencies
#  ansible.builtin.pip:
#    requirements: /app/requirements.txt
#    executable: pip3.6
#
#- name: SystemD setup
#  ansible.builtin.include_tasks: "systemd.yml"
#
#- name: Load Schema
#  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
#  when: schema_load


