
#LOAD_SCHEMA

- name: Install Maven
  ansible.builtin.debug:
    name: maven
    state: Installed

- name: App pre-Req
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: Maven Build
  ansible.builtin.shell: mvn clean package
  args:
    chdir: /app

- name: systemd setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load


